config/routes.rb
Rpcserver::Application.routes.draw do
  resources :rpc_responses
  match '/' => 'rpc_responses#xe_index'

end

app/models/rpc_response.rb
class RpcResponse < ActiveRecord::Base
  attr_accessible :methodName, :params, :request, :response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rpc_responses_controller.rb
class RpcResponsesController < ApplicationController
  exposes_xmlrpc_methods :method_prefix => "monitor."
  
  def listMethods
    do_params
    2
  end
  
  def methodHelp(mString)
    do_params
    2
  end
  
  def methodSignature(mString)
    do_params
    2
  end

  def listActiveUsers
    #do_params
    2
  end
  
  def checkActiveUser(uString)
    logger.info uString
    #do_params
    2
  end

  def getLoadAverages
    do_params
    2
  end

  def getDiskSpace
    do_params
    2
  end

  def getSelectedDiskSpace(uString)
    do_params
    2
  end
   
  # GET /rpc_responses
  # GET /rpc_responses.json
  def index
    @rpc_responses = RpcResponse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rpc_responses }
    end
  end

  # GET /rpc_responses/1
  # GET /rpc_responses/1.json
  def show
    @rpc_response = RpcResponse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @rpc_response }
    end
  end

  # DELETE /rpc_responses/1
  # DELETE /rpc_responses/1.json
  def destroy
    @rpc_response = RpcResponse.find(params[:id])
    @rpc_response.destroy

    respond_to do |format|
      format.html { redirect_to rpc_responses_url }
      format.json { head :no_content }
    end
  end
  
  protected
  
  def do_params
     #{"methodCall"=>{"methodName"=>"monitor.checkActiveUser", "params"=>{"param"=>{"value"=>{"array"=>{"data"=>{"value"=>{"string"=>"3"}}}}}}}}
    params[:rpc_response] = {} unless params[:rpc_response]
    params[:rpc_response][:methodName] = params[:methodCall][:methodName]
    params[:rpc_response][:params] = params[:methodCall][:params][:param].collect { |p| p[:value][:string] }.join("||#||")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rpc_responses_helper.rb
module RpcResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpcserver</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rpc_responses/_form.html.erb
<%= form_for(@rpc_response) do |f| %>
  <% if @rpc_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rpc_response.errors.count, "error") %> prohibited this rpc_response from being saved:</h2>

      <ul>
      <% @rpc_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :request %><br />
    <%= f.text_area :request %>
  </div>
  <div class="field">
    <%= f.label :methodName %><br />
    <%= f.text_field :methodName %>
  </div>
  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_area :params %>
  </div>
  <div class="field">
    <%= f.label :response %><br />
    <%= f.text_area :response %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rpc_responses/edit.html.erb
<h1>Editing rpc_response</h1>

<%= render 'form' %>

<%= link_to 'Show', @rpc_response %> |
<%= link_to 'Back', rpc_responses_path %>

app/views/rpc_responses/index.html.erb
<h1>Listing rpc_responses</h1>

<table>
  <tr>
    <th>Request</th>
    <th>Methodname</th>
    <th>Params</th>
    <th>Response</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rpc_responses.each do |rpc_response| %>
  <tr>
    <td><%= rpc_response.request %></td>
    <td><%= rpc_response.methodName %></td>
    <td><%= rpc_response.params %></td>
    <td><%= rpc_response.response %></td>
    <td><%= link_to 'Show', rpc_response %></td>
    <td><%= link_to 'Edit', edit_rpc_response_path(rpc_response) %></td>
    <td><%= link_to 'Destroy', rpc_response, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rpc response', new_rpc_response_path %>

app/views/rpc_responses/new.html.erb
<h1>New rpc_response</h1>

<%= render 'form' %>

<%= link_to 'Back', rpc_responses_path %>

app/views/rpc_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Request:</b>
  <%= @rpc_response.request %>
</p>

<p>
  <b>Methodname:</b>
  <%= @rpc_response.methodName %>
</p>

<p>
  <b>Params:</b>
  <%= @rpc_response.params %>
</p>

<p>
  <b>Response:</b>
  <%= @rpc_response.response %>
</p>


<%= link_to 'Edit', edit_rpc_response_path(@rpc_response) %> |
<%= link_to 'Back', rpc_responses_path %>